### ISSUE TITLE
AutoFocus is not Working

### ISSUE THREAD

**Issue by abumoallim** [LiewJunTung/pin_code_text_field#16]
When the OTP page open, the keyboard should by default open and cursor for the first box should be selected.

and if keyboard is open already open from previous page, it should focus the first edittext without on it explicitly.

**Comment by elrafal** [comment]
I've resolved same problem like this:

@override
  void initState() {
  super.initState();
  myFocusNode = new FocusNode();
  WidgetsBinding.instance.addPostFrameCallback((_) => focusBug());
}

void focusBug() {
  myFocusNode.unfocus();
  FocusScope.of(context).requestFocus(myFocusNode);
}

@override   
void dispose() {
  myFocusNode.dispose();
  super.dispose();
}
