### ISSUE TITLE
implement OneTimeCode like ios

### ISSUE THREAD

**Issue by kekedaine** [LiewJunTung/pin_code_text_field#18]
please implement .OneTimeCode like ios

**Comment by LiewJunTung** [comment]
I'm not sure what's a OneTimeCode. Do you mean something like this? https://pub.dev/packages/sms_autofill

**Comment by longlehoang** [comment]
> I'm not sure what's a OneTimeCode. Do you mean something like this? https://pub.dev/packages/sms_autofill

Thank you for creating a very helpful package. I think SMS autofill is a great idea.
Android also allow auto copy pin code from SMS, but I can't paste it into the pin box. It would be a good feature for user convenience .

**Comment by LiewJunTung** [comment]
Hi, thinks for clarifying. Let's see, you can wrap the `PinCodeTextField` with `GestureListener`.

Then you can either fill it up directly or launch a dialog and ask users if they want to copy to the PinCodeTextField.

I can put this in as part of the package but it might sacrifice the ability to customize how devs want it to behave. 

Let me know if it works for you.

**Comment by divlov-axeno** [comment]
As we all know in ios for the otp autofill to work, we need to add `singleFactorCodeTextField.textContentType = .oneTimeCode` to the text field and for it to work in flutter, we add autofillHints to the textField widget with [AutofillHints.oneTimeCode]. How to do that in this PinCodeTextField?

**Comment by divlov** [comment]
As we all know in ios for the otp autofill to work, we need to add singleFactorCodeTextField.textContentType = .oneTimeCode to the text field and for it to work in flutter, we add autofillHints to the textField widget with [AutofillHints.oneTimeCode]. How to do that in this PinCodeTextField?

**Comment by divlov** [comment]
As we all know in ios for the otp autofill to work, we need to add singleFactorCodeTextField.textContentType = .oneTimeCode to the text field and for it to work in flutter, we add autofillHints to the textField widget with [AutofillHints.oneTimeCode]. How to do that in PinCodeTextField?
