### ISSUE TITLE
how to set pinBoxWidth automatic .

### ISSUE THREAD

**Issue by welldone217** [LiewJunTung/pin_code_text_field#2]
Hope automatic width

**Comment by LiewJunTung** [comment]
Can you elaborate on that?

**Comment by welldone217** [comment]
pinBoxWidth=70 then maxlength=4 is ok. maxlength=6 is out screen.

i want the pin box Response 。

**Comment by LiewJunTung** [comment]
Added autowidth in version `1.2.1`, check out the documentation for more information. #3

**Comment by welldone217** [comment]
thx very. @LiewJunTung
