### ISSUE TITLE
Change specific cell input value

### ISSUE THREAD

**Issue by tigrenok00** [LiewJunTung/pin_code_text_field#24]
Hi,
The only way to change the entered values is to use clear button, as it seems. Is there an option to change value of specific cell when clicked? (Click a cell, show it as selected, override value by typing a new number, and shift the focus to the next cell).
Thanks!

**Comment by creativeaura** [comment]
@tigrenok00 

You can use the controller to change the value or clear the fields programmatically. 

`controller.text = ""`

**Comment by LiewJunTung** [comment]
Unfortunately, I won't be featuring this particular feature. It tends to mess with the focus and animation. But if you do have a solution, please do a pull request! I'll close this for now.
