### ISSUE TITLE
1.3.7: Exception: TextEditingController can only contains numeric

### ISSUE THREAD

**Issue by tigrenok00** [LiewJunTung/pin_code_text_field#25]
Hi,
When clicking on a special character on a numeric keyboard (like comma, dot or "-") the following exception is raised and its not possible to work with the control.
Desired behavior: it should ignore non-numeric characters completely.
Can you please fix it soon?
Thanks!

`══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
I/flutter (17864): The following _Exception was thrown while dispatching notifications for TextEditingController:
I/flutter (17864): Exception: TextEditingController can only contains numeric
I/flutter (17864):
I/flutter (17864): When the exception was thrown, this was the stack:
I/flutter (17864): #0      PinCodeTextFieldState._initTextController 
package:pin_code_text_field/pin_code_text_field.dart:237
I/flutter (17864): #1      PinCodeTextFieldState.initState.<anonymous closure>.<anonymous closure> `

**Comment by samuelg123** [comment]
Same with you.

**Comment by samuelg123** [comment]
For those who need this fix now, you can use my repo.
#### pubspec.yaml
``` 
pin_code_text_field:
    git:
      url: git://github.com/samuelg123/pin_code_text_field.git
      ref: master
```

**Comment by LiewJunTung** [comment]
Merged the PR. Thanks!
