### ISSUE TITLE
background color for pinbox

### ISSUE THREAD

**Issue by shrutikateiosys** [LiewJunTung/pin_code_text_field#31]
I want to set background color for box please kindly provide option to set background color.

**Comment by LiewJunTung** [comment]
Hi, you can use the `pinBoxDecoration` to set the looks and feels for the box. Including the color of the boxes.

**Comment by TanguAchilis** [comment]
hi, i would like to start by thanking the developers of this widget for the wonderful job. 
i think it would more user friendly if some new parameter like pinBoxColor and pinBoxRadius can be added to this widget.
![image](https://user-images.githubusercontent.com/43493154/66659942-40bf9100-ec3c-11e9-882c-84c96077e7c3.png)

**Comment by LiewJunTung** [comment]
@TanguAchilis Sure, will consider it. Thanks!

**Comment by LiewJunTung** [comment]
added pinBoxColor & pinBoxRadius
