### ISSUE TITLE
The named parameter 'pinCodeTextFieldLayoutType' isn't defined.

### ISSUE THREAD

**Issue by sapnapositive** [LiewJunTung/pin_code_text_field#35]
I have trying code as per example, getting error on following line:

pinCodeTextFieldLayoutType: PinCodeTextFieldLayoutType.AUTO_ADJUST_WIDTH,
 
Undefined name 'PinCodeTextFieldLayoutType'.
The named parameter 'pinCodeTextFieldLayoutType' isn't defined.

**Comment by Wisdom0063** [comment]
Having this same issue
Any fix?

**Comment by LiewJunTung** [comment]
Sorry, I have updated the README, `PinCodeTextFieldLayoutType.AUTO_ADJUST_WIDTH` has been removed. Thanks for reporting the issue! :)

**Comment by nihalreddy33** [comment]
@LiewJunTung what's the alternative to PinCodeTextFieldLayoutType.AUTO_ADJUST_WIDTH?

**Comment by nihalreddy33** [comment]
@LiewJunTung without AutoAdjust the pin boxes are aligned properly

**Comment by nihalreddy33** [comment]
@LiewJunTung without AutoAdjust the pin boxes are not aligned properly.

**Comment by luffynas** [comment]
> @LiewJunTung what's the alternative to PinCodeTextFieldLayoutType.AUTO_ADJUST_WIDTH?

you can use this code as altenative https://github.com/LiewJunTung/pin_code_text_field/blob/27cf747acaf79592efead31096968232557e0896/example/lib/main.dart#L183
