### ISSUE TITLE
clear pin text box

### ISSUE THREAD

**Issue by chanyap92** [LiewJunTung/pin_code_text_field#9]
how to clear my pin text box ? i try controller.text = '' but doesnt work, the controller is clear but the pin text box still showing * in it

**Comment by LiewJunTung** [comment]
Done, check out version 1.3.1. 😄

**Comment by chanyap92** [comment]
> Done, check out version 1.3.2. 😄

but after updated now all my pinbox come out error Exception: TextEditingController can only contains numeric

**Comment by doubletcjs** [comment]
enablePinAutofill: false
